name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_TOKEN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/personal-registration:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/personal-registration:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST_DIGITALOCEAN_PERSONAL_REGISTRATION }}
          username: ${{ secrets.USER_DIGITALOCEAN_PERSONAL_REGISTRATION }}
          key: ${{ PASSWORD_DIGITALOCEAN_PERSONAL_REGISTRATION }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/personal-registration:latest
            docker stop personal-registration || true
            docker rm personal-registration || true
            docker run -d --name personal-registration -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/personal-registration:latest
